name: build

on:
  push:
    paths:
      - "manylinux/cu122/*.Dockerfile"
      - "manylinux/cu121/*.Dockerfile"
      - "manylinux/cu120/*.Dockerfile"
      - "manylinux/cu118/*.Dockerfile"
      - "manylinux/cu117/*.Dockerfile"
      - "manylinux/cu116/*.Dockerfile"
      - "manylinux/cu110/*.Dockerfile"
      - "manylinux/cu114/*.Dockerfile"
      - "manylinux/cu102/*.Dockerfile"
      - ".github/workflows/build.yaml"
  schedule:
    - cron: '1 0 1 * *' # run on every month

jobs:
  build-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda-version: ['102', '114', '116', '117', '118', '120', '121', '122']
    env:
      HUB_DOCKER_IMAGE_NAME: scrin/manylinux2014-cuda:cu${{ matrix.cuda-version }}
      DOCKER_IMAGE_NAME: manylinux2014-cuda:cu${{ matrix.cuda-version }}
      BASE_DOCKER_FILE_PATH: "manylinux/cu${{ matrix.cuda-version }}/base.Dockerfile"
      DEV_DOCKER_FILE_PATH: "manylinux/cu${{ matrix.cuda-version }}/devel.Dockerfile"
      VERSION: "1.0.0"
    steps:
      - uses: actions/checkout@master
      - name: Build Docker
        run: |
          docker build manylinux/cu${{ matrix.cuda-version }} --file ${{env.BASE_DOCKER_FILE_PATH}} --tag ${{env.DOCKER_IMAGE_NAME}}-runtime
          docker build manylinux/cu${{ matrix.cuda-version }} --file ${{env.DEV_DOCKER_FILE_PATH}} --tag ${{env.DOCKER_IMAGE_NAME}}-devel
          docker tag ${{env.DOCKER_IMAGE_NAME}}-devel ${{env.HUB_DOCKER_IMAGE_NAME}}-devel-${{ env.VERSION }}
      - name: Login to Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        run: |
          docker push ${{env.HUB_DOCKER_IMAGE_NAME}}-devel-${{ env.VERSION }}
